feat: Tag 엔티티 설계 및 API 구현
DDD-5/null-moodof-backend pull request #29
Opened 2021-04-27 12:56 UTC by gwanhyeon

resolve #28
feat: Tag 엔티티 설계 및 API 구현

다른 엔티티도 다 짜놓기전에 한번 리뷰 진행하고 다른것들 한꺼번에 진행하는것이 나아보여서 리뷰 남겨놓겠습니다~

중복되는 코드가 있거나 조금 더 나은코드가 있으면 바로 반영해보겠습니다~

최대한 규칙에 맞춰서 짜려고 하였고 시간나실때 리뷰 남겨주세요!🙇‍♂️

2021-04-27 13:07 UTC, gwanhyeon commented
아 그리고 생성,수정시에 해당 tag id or tagName으로 할껀지를 정해야할 것 같아요. @Pathvariable로 처리할건지 body에 넣어서 값을 받아올껀지 등등이요!

2021-04-27 16:21 UTC, kouz95 requested changes
고생하셨습니다 👍

리뷰 확인해 주시고, 이야기 나눌 부분 있으시면 코멘트 부탁드리겠습니다 🙏

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +        return ResponseEntity.badRequest().build();
이름이 중복되는 태그를 요청한 경우 클라이언트가 bad request만 받게 될 것 같은데 의도하신 부분인가요?
중복된 이름의 태그라는 정보를 전달해줘야될 것 같아요!

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/application/TagService.java
> +    }
```suggestion
    public void delete(Long id, Long userId) {
        Tag tag = tagRepository.findTagByIdAndUserId(id, userId)
                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 태그 정보입니다. " + id + " / " + userId));
        if (tag.isUserIdNotEquals(userId)) {
            throw new IllegalArgumentException("~");
        }
        tagRepository.deleteById(tag.getId());
    }
```
이렇게도 가능할 것 같습니다. 🙂

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/application/TagService.java
> +    public TagDTO.TagResponse update(TagDTO.@Valid UpdateReqeust reqeust, Long userId) throws ValidationExceptionResponse {
Service에도 `@Valid` 가 필요할까요?

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +    public ResponseEntity<TagDTO.TagResponse> update(@RequestBody @Valid TagDTO.UpdateReqeust request, @LoginUserId Long userId) {
update의 EndPoint가 `/api/tags/{id}`가 되는게 더 적절해 보입니다

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/domain/model/tag/Tag.java
> +    }
userId를 변경하는 경우가 있을까요?

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/domain/model/tag/Tag.java
> +    private String tagName;
저는 그냥 name이 나아보이네요 🙂 

- `tag.getName()`
- `tag.getTagName()`

tag가 없더라도 헷갈리지 않을 것 같은데, 어떻게 생각하시나요?

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/domain/model/tag/TagRepository.java
> +    Optional<Tag> findTagByTagNameAndUserId(String TagName, Long userId);
```suggestion
    Optional<Tag> findTagByTagNameAndUserId(String tagName, Long userId);
```

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/domain/model/tag/TagRepository.java
> +    Long deleteByIdAndUserId(Long tagName, Long UserId);
```suggestion
    Long deleteByIdAndUserId(Long id, Long userId);
```

2021-04-27 16:21 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/AcceptanceTest.java
> +                    .andReturn();
```suggestion
                    .andExpect(MockMvcResultMatchers.status().isOk())
                    .andReturn();
```

PUT 요청이니 Status가 Created보단 Ok가 되어야할 것 같아요

2021-04-27 16:21 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/AcceptanceTest.java
> +    }
수정이 post를 사용하고 있네요!

2021-04-27 16:21 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +                .build().toUriString();
특별히 param이 추가되거나 그런 상황은 아니니 UriCompoentsBuilder는 사용할 필요가 없어보입니다.

2021-04-27 16:21 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +        assertAll(
검증하고자 하는 것이 1개일땐 굳이 assertAll을 사용하지 않아도 괜찮을 것 같아요

2021-04-27 16:21 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +                () -> assertThat(response.get(0)).isNotNull()
NotNull로 끝나기 보단 태그의 개수가 총 4개이다, 첫번째 태그는 ~이다와 같은 부분까지 테스트하는게 더 정확한 테스트가 될 것 같아요!

2021-04-27 16:21 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +        // when
```suggestion
        // when
        TagDTO.TagResponse response = 태그_생성(userId, "tagName1");
```

맥락상 when이 더 적절한 것 같습니다 🙂 (태그 생성을 할때 ~)

given은 로그인이 되어있다 (BeforeEach에서 진행된)로 봐도 될 것 같아요

2021-04-27 16:21 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +    public void 태그를_수정() throws Exception {
태그 이름이 수정되는게 아니라 서로 다른 이름을 가진 태그가 생성되고 있습니다 ㅜ

2021-04-27 16:21 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +    public void 태그_리스트_출력(Long userId) throws Exception {
```suggestion
    private void 태그_리스트_출력(Long userId) {
```

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/application/dto/TagDTO.java
> +    public static class UpdateReqeust{
```suggestion
    public static class UpdateRequest {
```
오타가 있네용

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/infrastructure/advice/ValidationExceptionResponse.java
> +public class ValidationExceptionResponse extends Throwable {
Throwable을 상속받은 이유가 있나요?

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +        return ResponseEntity.created(URI.create(API_TAG + "/" + response.getId())).body(response);
만약 Validation에 실패하게 되면 NPE가 발생할 것 같습니다 (`response.getId()`)

2021-04-27 16:21 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +            return ResponseEntity.created(URI.create(API_TAG + "/" + response.getId())).body(response);
생성이 아니고 수정이니 응답은 OK가 더 적절해보입니다 🙂

2021-04-28 04:29 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/TagService.java
> +    }
혹시 궁금한게 옵셔널로 안감싸고 orElseThrow로 보내버리면 옵셔널로 처리할 수 있나보네요! 아니면 다른이유가 있는가요?
엇 이렇게 코드 제안도 가능했군요😦😦

2021-04-28 04:31 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +        return ResponseEntity.badRequest().build();
살짝 의도된 코드이긴합니다. 성공시에 return을 처리해버리니 나머지 예외들은 badRequest로 보내려고하였는데, 중복된 이름의 태그 정보를 어떤식으로 던져주는게 좋을련지요 헤더나, 바디, 등등 어떻게 수정시 올바른방법일까 고민이긴 했습니다. ㅎㅎ

2021-04-28 04:31 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/TagService.java
> +    public TagDTO.TagResponse update(TagDTO.@Valid UpdateReqeust reqeust, Long userId) throws ValidationExceptionResponse {
오타가 있었네요~

2021-04-28 04:32 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +    public ResponseEntity<TagDTO.TagResponse> update(@RequestBody @Valid TagDTO.UpdateReqeust request, @LoginUserId Long userId) {
반영하겠습니다~

2021-04-28 04:33 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/domain/model/tag/Tag.java
> +    }
불필요한 코드같긴 하네요 왜 만들어놨을까요.. 삭제하는것으로 수정할께요~

2021-04-28 04:38 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +            return ResponseEntity.created(URI.create(API_TAG + "/" + response.getId())).body(response);
이 부분은 좀 얘기를 나누어보고 싶었던게 있긴합니당.
ok() 같은경우는 200을 떨궈서 성공적으로 바디로 200을 떨구는 부분이긴한데,  201 created부분이 post, put 부분도 포함될 수 있는 부분이긴해서요. 200이 나을지 201이 나을지 고민을 하긴했습니당 어떻게보면 200같기도하고 어떻게보면 201같기도 합니다🙇‍♂️

https://developer.mozilla.org/ko/docs/Web/HTTP/Status

2021-04-28 04:39 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/infrastructure/advice/ValidationExceptionResponse.java
> +public class ValidationExceptionResponse extends Throwable {
외부 클래스를 만들어서 Exception클래스를 만들기위해서는 Thrawable을 상속받아야 저희가 사용하는 로직에 적용이 가능합니다! 다르게 하는 방법이 있을까용?

2021-04-28 05:54 UTC, gwanhyeon commented on src/test/java/com/ddd/moodof/acceptance/AcceptanceTest.java
> +    }
오타가 있었나보네요 수정하겠습니다~

2021-04-28 05:54 UTC, gwanhyeon commented on src/test/java/com/ddd/moodof/acceptance/AcceptanceTest.java
> +                    .andReturn();
이것도 리뷰코멘트 남긴사항과 유사해보여서 답변주시면 감사하겠습니다!

2021-04-28 05:55 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/domain/model/tag/TagRepository.java
> +    Optional<Tag> findTagByTagNameAndUserId(String TagName, Long userId);
name으로 통일하겠습니다

2021-04-28 05:55 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/domain/model/tag/TagRepository.java
> +    Long deleteByIdAndUserId(Long tagName, Long UserId);
부분부분적용 안된부분을 놓쳤네요

2021-04-28 05:56 UTC, gwanhyeon commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +                .build().toUriString();
UriComponentBuilder가 앞에 현재 로컬 ip까지 붙여서 제공되는줄 알았는데, 디버깅찍어보니 그게 아니였네요!

2021-04-28 05:56 UTC, gwanhyeon commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +                () -> assertThat(response.get(0)).isNotNull()
변경하였습니다.

2021-04-28 06:54 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +        return ResponseEntity.badRequest().build();
exceptionHandler를 만들어 놓았습니다!
RuntimeException을 상속 받은 예외들 (Illegal~, 혹은 상속 받아 만든 customException)의 경우 throw만 해도 exceptionHandler에 의해 bad request에 body에는 message가 담깁니다 🙂

[@ControllerAdvice, @ExceptionHandler를 이용한 예외처리 분리, 통합하기(Spring에서 예외 관리하는 방법, 실무에서는 어떻게?)](https://jeong-pro.tistory.com/m/195)

2021-04-28 06:56 UTC, kouz95 commented on src/main/java/com/ddd/moodof/application/TagService.java
> +    }
Optional.orElseThrow -> Optional로 감싼 객체가 empty 일때 throw를 하고 존재하면 객체를 반환하는 식으로 알고 있습니다!

2021-04-28 07:00 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/infrastructure/advice/ValidationExceptionResponse.java
> +public class ValidationExceptionResponse extends Throwable {
RuntimeException이나 IllegalArgumentException 같은 UncheckedException을 상속받는건 어떨까요?
ExceptionHandler를 활용할 수 있을것 같아서요!

2021-04-28 07:00 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +        return ResponseEntity.created(URI.create(API_TAG + "/" + response.getId())).body(response);
이부분 ok()로 처리해놓았습니다

2021-04-28 07:02 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +            return ResponseEntity.created(URI.create(API_TAG + "/" + response.getId())).body(response);
created는 요청에 의해 자원이 '생성'되었을때에 해당하니 수정의 경우엔 OK 정도가 좋지 않을까요?

![image](https://user-images.githubusercontent.com/52931057/116360462-e9dbd580-a83a-11eb-8842-f0ae17f26b4a.png)

2021-04-28 07:06 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/presentation/TagController.java
> +            return ResponseEntity.created(URI.create(API_TAG + "/" + response.getId())).body(response);
payload 담긴 정보를 이용해서 새로운 자원을 만들어 기존에 존재하던 자원을 대체하는 과정을 생성한다라고 생각을 했었는데 수정의 경우 ok()나 noContent()정도로 처리하면 되겠네요! ok()로 반영은 해놓았습니다!

2021-04-29 09:02 UTC, kouz95 approved these changes
반영해주신것 확인했습니다 👍
테스트 관련하여 간단한 리뷰 2개 남겼는데, 컨플릭 잡으시면서 확인해주시면 좋을 것 같습니다 🙂

고생하셨습니다!

2021-04-29 09:02 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +        TagDTO.TagResponse updateList = 태그_수정(userId, createList.getId(),"name2");
```suggestion
        TagDTO.TagResponse updateList = 태그_수정(createList.getId(), userId, "name2");
```

현재는 둘다 ID가 1이라서 통과한것 같습니다! 테스트 메소드의 동작을 봤을땐 인자가 서로 바뀌어야 할 것 같네요 🙂

2021-04-29 09:02 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +        assertThat(createList.getName()).isNotEqualTo(updateList.getName());
```suggestion
        assertThat(updateList.getName()).isEqualTo("name2");
```

는 어떠신가요? 업데이트 요청을 했더니, 요청한대로 이름이 변경되어 응답이 나왔더라~ 정도로 생각할 수 있을것 같아요

2021-04-29 10:54 UTC, gwanhyeon commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +        TagDTO.TagResponse updateList = 태그_수정(userId, createList.getId(),"name2");
놓친부분이 있었네요 수정해서 반영해놓겠습니다 💁‍♂️

2021-04-29 10:55 UTC, gwanhyeon commented on src/test/java/com/ddd/moodof/acceptance/TagAcceptanceTest.java
> +        assertThat(createList.getName()).isNotEqualTo(updateList.getName());
요청흐름상 업데이트 기준으로 테스트하는것이 좋긴하겠네요! 생성기준으로 테스트할 필요는 없어보입니다 수정해놓겠습니다!!

2021-04-29 11:15 UTC, merged