feat: StroagePhoto Page 조회 구현
DDD-5/null-moodof-backend pull request #31
Opened 2021-04-28 11:42 UTC by kouz95

resolve #30 

- 휴지통 추가, 취소, 목록 조회 API 구현
- 사진 보관함 페이지 조회의 경우 휴지통에 속하지 않은 사진만 반환

2021-04-28 12:10 UTC, kouz95 commented
RequestParam에 Valid 적용 (StoragePhoto, TrashPhoto)

2021-04-29 10:51 UTC, gwanhyeon requested changes
전체적인 기능 동작 확인하였습니다~ 페이징 처리시 최적화라던지 간편하게 처리할 수 있는부분이 많아보이긴 해서 의견 한번 나누면 좋긴할 것 같습니다!  고생많으셨습니다!! 👍👍

2021-04-29 10:51 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/StoragePhotoQueryRepositoryImpl.java
> +
`java.lang.Object , org.springframework.data.repository.support.PageableExecutionUtils`에서 제공하는
`SpringData PageableExecutionUtils`라는 유틸이 있는데 카운트에 최적화할 수 있는게 있긴하네요!

> PageableExecutionUtils
 
[PageableExecutionUtils](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/support/PageableExecutionUtils.html)

2021-04-29 10:51 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/StoragePhotoQueryRepositoryImpl.java
> +package com.ddd.moodof.adapter.infrastructure.repository;
레파지토리부분을 인프라 패키지에서 파일 관리하는 이유가 따로있을까용??

2021-04-29 10:51 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/StoragePhotoQueryRepositoryImpl.java
> +    public StoragePhotoDTO.StoragePhotoPageResponse findPageExcludeTrash(Long userId, int page, int size, String sortBy, boolean descending) {
각각 파라미터를 받지 않고 Pageable로 한꺼번에 받아오면 조금더 관리하기 편하지 않을까 싶긴합니다! 
이런식으로 처리할 수도 있는것 같아보여서 의견남깁니다👍
[참고](https://www.popit.kr/spring-boot-jpa-%ED%8E%98%EC%9D%B4%EC%A7%95-api-%EB%A7%8C%EB%93%A4%EA%B8%B0/)

2021-04-29 10:51 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/TrashPhotoQueryRepositoryImpl.java
> +        List<TrashPhotoDTO.TrashPhotoResponse> trashPhotoResponses = new Querydsl(em, new PathBuilderFactory().create(TrashPhoto.class))
바로 리스트로 받을 수 있을 줄 알았는데 프로젝션을 써서 리턴받을때 JPAQuery객체로 반환을 받네요! PathBuilderFactory를 써본적이 없어서 매번 이런식으로 다 받아와야하나요?

2021-04-29 10:51 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/TrashPhotoQueryRepositoryImpl.java
> +        )).from(trashPhoto)
offset(), limit(), fetchResults()를 사용해서 페이징정보랑 total count를 한꺼번에 조회해오는 방식도 있는것 같더라구요!

2021-04-29 10:51 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/presentation/api/StoragePhotoAPI.java
> +            @ApiIgnore Long userId,
`@LoginUserId `이게 빠져있는게 아닌가용?

2021-04-29 10:51 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/presentation/api/StoragePhotoAPI.java
> +    ResponseEntity<Void> deleteById(@ApiIgnore Long userId, @PathVariable Long id);
위와 동일합니다

2021-04-29 18:14 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/StoragePhotoQueryRepositoryImpl.java
> +
혹시 어떤식으로 활용할 수 있을까요? 사용해본 적이 없어서요 🥲
짧게나마 getPage 메소드를 확인해 봤을땐 모든 content가 불러와져 있을때, Page 객체로 반환하는 메소드로 보이는데
제가 `jpaQuery.fetchCount()` 와 `.applyPagination(pageable, jpaQuery).fetch()` 를 나눈 것은, 모든 객체를 로드하지 않은 상태로, count쿼리와 페이지에만 해당하는 객체를 fetch하는 쿼리를 분리하여 데이터를 가져오기 위함이었습니다!

2021-04-29 18:16 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/StoragePhotoQueryRepositoryImpl.java
> +package com.ddd.moodof.adapter.infrastructure.repository;
querydsl 이라는 기술에 종속된 코드가 생겨나게 되니, infra에 두는게 좋다고 생각했습니다.
domain이 기술에 의존하지 않도록 인터페이스와 구현부를 나눴습니다([DIP](https://ko.wikipedia.org/wiki/%EC%9D%98%EC%A1%B4%EA%B4%80%EA%B3%84_%EC%97%AD%EC%A0%84_%EC%9B%90%EC%B9%99))

2021-04-29 18:20 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/StoragePhotoQueryRepositoryImpl.java
> +    public StoragePhotoDTO.StoragePhotoPageResponse findPageExcludeTrash(Long userId, int page, int size, String sortBy, boolean descending) {
보내주신 링크에서 Controller에서 부터 Pageable로 받는 것은 클라이언트가 힘들수도 있을것 같고 (스펙을 Pageable에 맞춰야 되는것으로 보입니다)

리뷰 달아주신 라인 부분에서부터 Pageable로 인자를 받는 것은, service에서 PageRequest를 만들어서 넘기면 되겠네요!
괜찮으시면 repository의 인자를 Pageable로 수정하는 쪽으로 해보겠습니다 🙂

2021-04-29 18:22 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/TrashPhotoQueryRepositoryImpl.java
> +        List<TrashPhotoDTO.TrashPhotoResponse> trashPhotoResponses = new Querydsl(em, new PathBuilderFactory().create(TrashPhoto.class))
Querydsl 객체에 applyPagination 메소드가 있더라구요. 
구현하면서 이거저거 많이 해봤는데 이 방법이 pagination 처리가 가장 깔끔하다고 느껴졌었어요 🙂

2021-04-29 18:24 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/infrastructure/repository/TrashPhotoQueryRepositoryImpl.java
> +        )).from(trashPhoto)
offset과 limit을 사용하게되면 orderBy를 직접 정의해줘야하는데 (Sort가 있어서요) 그 부분이 만만치 않더라구요 ㅜ..

2021-04-29 18:26 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/presentation/api/StoragePhotoAPI.java
> +            @ApiIgnore Long userId,
이 부분은 Swagger 문서화를 만들기 위해 작성되는 부분이라고 생각해서 ArgumentResolver 관련 어노테이션을 달지 않았습니다. 
달아도 상관은 없을 것 같네요 🙂

2021-04-29 18:28 UTC, kouz95 commented
쓰레기통 복수 이동 기능을 빼먹었더라구요 😅
RequestParam에 Valid 적용 (StoragePhoto, TrashPhoto) 이랑 복수 생성 부분 추가하여 다시 리뷰 요청 드리겠습니다 🙇‍♂️

2021-04-30 09:57 UTC, kouz95 commented
`@RequestParam` 에 `@Min` 을 사용해봤는데 동작을 안하더라구요! 혹시 다른 적용 방법이 있을까요?

- `@RequestParam @Min(0) int page`
- `@RequestParam @Valid @Min(0) int page`
- `@RequestParam @Valid @Min(0) Integer page`

로 시도해봤습니다!

2021-05-01 06:38 UTC, merged