feat: Board API 구현
DDD-5/null-moodof-backend pull request #42
Opened 2021-05-13 11:59 UTC by kouz95

resolve #36 

- 카테고리 삭제시 카테고리에 속한 보드도 삭제하도록 하였습니다.
- 카테고리 생성시 이름 중복이 가능하도록 변경하였습니다.

2021-05-14 08:22 UTC, gwanhyeon requested changes
몇가지 궁금한점도 있기도해서 리뷰남겨놓았으니 시간나실때 확인부탁드리겠습니다! 전체적으로 기능확인이랑 테스트코드 확인하였습니다 고생하셨습니다! 👍👍 카테고리 삭제부분 추가해주신부분도 확인했습니다.

2021-05-14 08:22 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/BoardService.java
> +        Board board = boardVerifier.toEntity(request.getPreviousBoardId(), request.getCategoryId(), request.getName(), userId);
해당 Service내에서 메소드를 만들지 않고 DI 모듈화시키시려고 나누신게 맞나요? Service내에서 메서드를 선언하지 않고BoardVerifier를 따로 선언하여 두신 이유가 궁금하긴합니당

2021-05-14 08:22 UTC, gwanhyeon commented on src/test/java/com/ddd/moodof/acceptance/AcceptanceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
`@DirtiesContext` 모든 테스트케이스가 끝날때 마다 Context 재생성하는 로직인가보네요. 회원가입시마다 새로운 컨텍스트를 생성하시려고 구현하신게 맞을까요? 확실히 테스트시에 실행속도에서 차이가 있네요~

[@DirtiesContext](https://docs.spring.io/spring-framework/docs/current/reference/html/testing.html#spring-testing-annotation-dirtiescontext)

2021-05-14 08:22 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/domain/model/board/BoardVerifier.java
> +@Component
Spring 측에서 추가적인 exception handling을 해줄 수도 있으니 비즈니스 로직에는 @Service가 더 적절하지 않을까요?  @Component를 붙일 수 있지만, @Service를 붙인다면 클래스들을 처리하는데 더 적합하도록 할 수 있고 aspects에 더 연관성을 부여할 수 있다고 생각이 듭니다! 의견나눠봤으면 좋겠어요!
`Thus, if you are choosing between using @Component or @Service for your service layer, @Service is clearly the better choice.`
공식문서에 @Component보다는 @Service가 더 나은 선택일수 있다고 해서요! 

참고: 1.10.1. @Component and Further Stereotype Annotations
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans

2021-05-15 11:33 UTC, kouz95 commented on src/main/java/com/ddd/moodof/application/BoardService.java
> +        Board board = boardVerifier.toEntity(request.getPreviousBoardId(), request.getCategoryId(), request.getName(), userId);
- Service내에서 메소드를 만들지 않고 클래스를 나누는 이유

Application Service를 최대한 얇게 유지하려고 노력하는 편입니다.
Application Service의 역할은
- 객체 간의 실행 흐름 제어
- 트랜잭션 처리 
- 접근 제어
- 이벤트 처리
가 되어야합니다.

도메인 로직을 응용 서비스에 두지 않고, domain model에 최대한 위임하거나, 위임이 불가능 한 경우엔 Domain Service를 만들어 도메인 로직을 표현하려고 하고 있습니다. (BoardSequenceUpdator 와 같은 경우 Domain Service)

[관련 영상](https://youtu.be/TdyOH1xZpT8?t=1520) - 25분 20초 ~

2021-05-15 11:42 UTC, kouz95 commented on src/test/java/com/ddd/moodof/acceptance/AcceptanceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
TrashPhoto에 관련한 테스트가 실패하는 케이스가 있더라구요.
같은 context를 공유하기 때문에 다른 테스트에서 휴지통 생성을 한 것이 영향을 주고 기대한 결과가 나오지 않아 실패하고 있었습니다.

이를 해결하기 위해,
1. `@Transactional` 사용
테스트에서 Transactional 어노테이션을 사용하게 되는경우 테스트 메소드 동작 이후 DB를 롤백 시킵니다.
하지만 Transactional 활성화로 인해 JPA 영속성 컨텍스트 활성화 등 기대하지 않은 동작 및 정확한 테스트가 되지 않을 수 있습니다. (lastModifiedDate와 같은 경우)
2. 테스트 후 clean up
`@AfterEach` 에 repository.deleteAll() 이라던지, 테스트 환경을 위해서 생성시켰던 리소스들을 정리한후 테스트를 끝낸다면 다른 테스트에 영향을 주지 않을 것 입니다. -> 가장 바람직한 방법이라고 생각하긴 합니다. 다만, 실수로 까먹는다거나 휴먼 에러가 발생할 가능성이 높긴 합니다.
3. context 분리 (DirtiesContext)
`AFTER_EACH_TEST_METHOD` 에서 알 수 있듯이, 하나의 테스트가 끝나면 context를 격리 시킵니다. 가장 쉽게 적용할 수 있는 방법이긴 한데 말씀해주신대로 테스트 실행속도가 느려집니다. (매번 context를 만들어 내는 것 같아요)

---

일단 급한건 개발이니, 가장 빠르게 적용할 수 있는 것을 선택하여 적용하였습니다.
기능 개발이 어느정도 끝나고, 유지 보수 단계에 들어가게 된다면 프로덕션 코드 리팩토링과 함께 테스트에 대해서도 개선하면 좋을것 같다고 생각합니다 🙂

2021-05-15 11:56 UTC, kouz95 commented on src/main/java/com/ddd/moodof/domain/model/board/BoardVerifier.java
> +@Component
사실 이 부분에 대해서의 best practice가 무엇인지 아직 잘 모르겠습니다.

저는 BoardVerifier가 도메인 로직 혹은 비지니스 로직을 담당한다고 생각하지 않습니다.

제가 Verifier로 명명하는 부분들은 입력에 대한 논리적 오류가 존재할때 입니다.
`/entities/{id}` 라는 요청에서 id가 존재하지 않는 경우나 request body로 연관 엔티티의 id를 담아 요청하는데, 해당하는 id를 가진 엔티티가 존재하지 않는 경우와 같은 부분입니다.

때문에, `@Service` (Application Service & Domain Service) 와의 구별을 위해 `@Component`를 사용하였습니다.

---

best practice를 아직 모르겠다고 말씀 드린건, ~Verifier와 같은 방식으로 처리하는게 맞는가? 에 대한 부분이 있습니다.
`@PathVariable`에 한하여, AOP를 이용해서 처리할 수 도 있고 Request Body의 경우 constraint validator (spring validation) 을 사용하여 처리할 수 도 있다고 생각합니다.

2021-05-18 16:13 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/BoardService.java
> +        Board board = boardVerifier.toEntity(request.getPreviousBoardId(), request.getCategoryId(), request.getName(), userId);
Application Service부분을 최대한 얇게 유지하면서 프로젝트를 구성으로 하니까 응집도는 높아지고 결합도는 낮춰지는 효과가 있어보이네요. 정확하게 잘 몰랐던 부분이였는데 좋은 의견 감사합니다 참고하겠습니다 :) 
확실히 말씀해주신데로 Application Service부분에서 얇게 유지하면 위임하니 트랜잭션부분 제어나 객체간의 실행 흐름제어 부분에 있어서 관심사의 분리가 뛰어나보입니다 👍

2021-05-18 16:22 UTC, gwanhyeon commented on src/test/java/com/ddd/moodof/acceptance/AcceptanceTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
1번 의견주신 Transaction JPA 영속성 부분에서 Commit&Rollback 동작에 있어서 정확한 테스트가 안되는 부분이 있었어서 충분히 공감이 가는 바입니다.
2번같은경우는 AfterEach를 통한  종료되어야할 리소스를 처리하는 부분에 있어서 테스트 실행 중 IoC에 할당된 Bean의 싱글톤을 초기화하는 부분이 직관적이고 다른테스트에 있어서 매번 새로운 객체를 생성하기때문에 Context의 관리가 용이할것으로 생각됩니다 3번은 테스트에 있어서 생명주기로 관리하기가 용이해보이네요!

추후에 유지보수시에 개선될 사항들을 함께 의견을 나누어보면 좋겠습니다 좋은 코멘트 달아주셔서 다양한 관점으로 확인해볼 수 있는 계기가 되었네요 ☺️

2021-05-18 16:35 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/domain/model/board/BoardVerifier.java
> +@Component
긴가민가했던 부분이 Application Service로직 플로우상에서 진행되는 것이기 때문에 Service의 관점에서 바라보아야하는것이 아닌가라는 의문이 들어서 코멘트 남겨놓았습니다. `/엔티티/{id}`에서 가져오면 해당되는 도메인 엔티티로직에서 관점을 분리하는것이 어떨까였고 `@Component` 와 같은 부분은 Application, Domain 로직을 굳이 벗어나야하나? 라는 생각이였는데 `Application Service & Domain Service`의 구별지어 Verifier의 관점을 분리시킨다 라고 생각해도 좋은 방법이지 않을까 싶네요! 
DDD의 관점에서 이러한 Verifier분리하는것이 정형화된 모델인가요? 궁금하긴하네요 ㅎㅎ
AOP나 DispatcherServlet에서 HandlerMapping을 사용하는 방법으로 처리할 수도 있다고 생각합니다.

2021-05-18 16:40 UTC, gwanhyeon approved these changes
DDD 아키텍처 관점에서 다양한 접근을 생각해볼 기회가 되었습니다. DDD 책을 읽고 싶어지게 되었네요 :) 길고 장황하게 여러 코멘트를 남기게 되었는데 아키텍처나 클린코드부분에서 미흡한 부분이 많다고 느껴지네요 🙂 바쁘실텐데 여러관점에서 좋은 의견남겨주셔서 감사드립니다 🙇‍♂️

2021-05-18 17:08 UTC, kouz95 commented on src/main/java/com/ddd/moodof/domain/model/board/BoardVerifier.java
> +@Component
검증에 관련된 부분을 어떻게 처리하는지 여러 사람들의 코드를 보다가 Verifier.toEntity() 로 처리하는 코드를 보고 가장 직관적이라고 생각되서 주로 사용합니다.
AOP나 spring validation을 사용해서 처리하는 것도 이전에 해보긴 했었는데, 아무래도 명확하게 코드로 표현되지 않고 어노테이션으로 처리가 되는 부분이 많아지게 됩니다.
때문에 한번 해두면 나중에 사용할때 편하긴 편한데 너무 직관적이지 못한거 아닌가, 코드를 처음보는 사람이 이해해기엔 복잡한 코드 아닌가 이런 생각이 들더라구요.

항상 정답은 없더라구요 ㅎㅎ.. 재밌습니다 코딩...

2021-05-18 17:08 UTC, merged