feat: 보관함 사진 상세 조회 구현
DDD-5/null-moodof-backend pull request #44
Opened 2021-05-16 16:22 UTC by kouz95

resolve #43 

- 쿼리 한번에 조회하려 하였으나, JPQL Projection 에서 List를 지원하지 않는다고 합니다. 
  - [링크](https://stackoverflow.com/questions/17116711/collections-in-querydsl-projections)
  - 추후 쿼리 개선하게 된다면 JPQL이 아니라 jdbc나 mybatis 같은걸 사용해서 직접 쿼리를 작성해야할 것 같습니다.
- 이전 아이디와 다음 아이디를 구하는 과정에서도 서브 쿼리에서 limit을 사용할 수 없는 이슈로 쿼리가 조금 복잡해졌습니다.
  - [링크](https://stackoverflow.com/questions/8555485/how-to-impose-limit-on-sub-query-of-jpa-query)
  - 이 역시, 직접 쿼리를 작성하게 된다면 개선시킬 수 있을 것 같습니다. (order by modifiedDate desc limit 1)

2021-05-20 10:15 UTC, gwanhyeon requested changes
PR 주신사항들 잘 살펴보았고 얘기나누어 보고싶은 사항들은 코멘트남겨놓았습니다.

상세조회부분은 요구사항이 변경되었으니 수정되어야할부분은 커밋남겨주시면 확인해보겠습니다!

리뷰가 늦어져 죄송합니다 🙇‍♂️ 고생하셨습니다 깔끔하네요!

2021-05-20 10:15 UTC, gwanhyeon commented on build.gradle
> +sourceSets {
sourceSets, querydsl부분을 변경하신 이유가 따로 있을까요? 어떤차이가 있나요?

```xml
sourceSets {
    main {
        java {
            srcDir generatedSourcesDir
        }
    }
}

querydsl {
    querydslSourcesDir = relativePath(generatedSourcesDir)
    library = "com.querydsl:querydsl-apt"
    jpa = true
}		

```

2021-05-20 10:15 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/domain/model/board/BoardRepository.java
> +    boolean existsByIdAndUserId(Long id, Long userId);
eixsts를 사용할 경우와 Optional ().ElseThrow를 사용하는것과 차이가 있을까요? 비즈니스 로직을 구현시에 존재하는것을 체크할 것인지 이것을 옵셔널로 걸어서 던져줄 것인지에 대한 고민을 했던부분이 있습니다. 개인적으로 어떤게 Best Practice라고 생각하시나요?

2021-05-20 10:15 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/dto/StoragePhotoDTO.java
> +        @QueryProjection
이부분만 QueryProjection을 사용하신 이유가 있을까요? Q클래스를 생성해야하기 때문에 의존성이 높아지지 않을까라는 생각이 드네요.

2021-05-20 10:15 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/infrastructure/persistence/querydsl/StoragePhotoQuerydslRepository.java
> +                .where(storagePhoto.userId.eq(userId).and(storagePhoto.lastModifiedDate.eq(lastModifiedDateBeforeStoragePhoto(userId, id))));
이전, 이후 부분 간략하게 로직 말씀해주실수 있을까요 수정날짜로 처리하고있는데 이부분이 명확하게 들어오질 않네요!

2021-05-21 06:44 UTC, kouz95 commented on build.gradle
> +sourceSets {
이 부분을 변경하게 된건 
```
implementation "com.querydsl:querydsl-jpa:4.4.0"
implementation "com.querydsl:querydsl-apt:4.4.0"
```
여기가 핵심이었습니다.
이전에는 apt가 4.1.4버전이었고, 상세 조회 구현시 버전 차이로 인한 에러가 발생했었습니다.
4.4.0 버전으로 되어있는 querydsl 적용 정보를 찾아 적용하였습니다.
Q클래스를 만들어내는 부분등 이외의 부분에선 한번에 적용하다보니 변경이 있었는데, 특정한 의도는 없었습니다. 이전 코드와 같은 동작을 할 것이라고 예상하였습니다 🥲

2021-05-21 06:48 UTC, kouz95 commented on src/main/java/com/ddd/moodof/domain/model/board/BoardRepository.java
> +    boolean existsByIdAndUserId(Long id, Long userId);
exists로만 끝나는 경우엔 exists를 사용하는 것이 더 좋다고 생각합니다.
Optional 객체도 생성 비용이 있고, find를 통해 조회를 했을 경우에도 객체를 로딩해야하고 영속성 컨텍스트에 올라가고 JPA 1차 캐시에도 등록이 됩니다.
물론, find해온 객체의 존재 유무를 확인하고, 해당 객체를 활용하여 어떤 일을 수행해야 할때는 exists는 필요없다고 생각합니다.

2021-05-21 06:53 UTC, kouz95 commented on src/main/java/com/ddd/moodof/application/dto/StoragePhotoDTO.java
> +        @QueryProjection
Projection에서 categories와 tags가 없는 생성자가 필요했습니다.
이 생성자는 Projection에서 리플렉션을 통해 사용되게 되고, 코드상으론 표현이 되지 않다보니 사용하지 않는 생성자라고 생각되어 삭제한다던지의 일이 발생할 수 있다고 생각하였습니다.

2021-05-21 07:06 UTC, kouz95 commented on src/main/java/com/ddd/moodof/adapter/infrastructure/persistence/querydsl/StoragePhotoQuerydslRepository.java
> +                .where(storagePhoto.userId.eq(userId).and(storagePhoto.lastModifiedDate.eq(lastModifiedDateBeforeStoragePhoto(userId, id))));
사진 보관함 조회시 storagePhoto의 수정 시간으로 정렬하여 조회하게 됩니다. (추가 구현에서 tag 조건이나 오래된 순이라던지 정렬 조건이 바뀌게 되면 이부분도 수정이 이루어져야합니다.)
수정 시간 기준 이전 사진, 다음 사진을 구하기 위해 -> userId는 일치하면서 휴지통에 등록되지 않았고, 수정시간이 id의 수정시간보다 작은 것 중 가장 큰 것 또는, id의 수정 시간보다 큰 것 중 가장 작은 것이 이전, 다음이 된다고 생각하고 작성하였습니다.

여기서 '큰 것 중 가장 작은 것' 이라는 것이 서브 쿼리에서 id의 수정시간보다 (작은/큰) 것들을 수정시간으로 정렬한 후 limit 1 을 사용하면 로직이 간단해지는데 PR에서 말씀드렸듯 서브 쿼리에서 limit 를 사용할 수 없어, 쿼리가 좀 뱅뱅 돌아가게 되었습니다..

2021-05-21 16:49 UTC, gwanhyeon approved these changes
궁금했던 부분이나 코멘트 남겨준 사항들에 있어서 제가 고민했던 부분들 코멘트 남겨놓았습니다. 큰 이슈 없으면 머지 진행해도 좋을 것 같아요! 고생 많으셨습니다. 🙋‍♂️

2021-05-21 16:49 UTC, gwanhyeon commented on build.gradle
> +sourceSets {
버전차이 문제가 발생했었군요 

번외 이야기이지만 querydsl 에 대한 버전 이슈들을 찾아보니
- 4.0.1 버전까지는 list 조회 시 .list() 메서드
- 4.0.2 버전부터는 fetch() 메서드로 이름이 변경
- Annotation Processing Tool(apt) JDK 1.6 버전부터 지원 이슈
- querydsl-jpa:4.1.3 사용 중에 서브 쿼리를 이용하기 위해 ne() -> not equals 메소드를 통해 같지 않음을 표현하는 상황에서 ne() 구현체는 실제로 equals로 구현되어 있었고 해당 사항들은 실제로 버그이며 4.2.1 버전에서 수정된 사례가 있네요
https://github.com/querydsl/querydsl/releases

이러한 것들중이나 이외에 버전차이가 있었나보네요!

2021-05-21 16:49 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/infrastructure/persistence/querydsl/StoragePhotoQuerydslRepository.java
> +                .where(storagePhoto.userId.eq(userId).and(storagePhoto.lastModifiedDate.eq(lastModifiedDateBeforeStoragePhoto(userId, id))));
사진보관함 조회시 생성순으로 정렬 조회하는 로직으로 생각하고 있었는데, 제가 잘못 생각한 부분이 있었네요! 수정시간을 기준으로 진행하면 말씀해주신것처럼 이전, 다음사진에 대한 처리로직이 이해가 가네용:)

querydsl이 컬렉션 및 연관관계 없이 서브쿼리하는것에 있어서 생각보다 핸들링하기가 힘들더라구요.. 저 역시 같은고민으로 삽질을... 하다가 일일이 직접 조회를 진행하면서 루프를 돌렸는데 서브쿼리에서 limit 처리를 할 수 없다니 같이 오픈소스에 기여 해보시지 않겠습니까 ㅎㅎ

2021-05-21 16:49 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/dto/StoragePhotoDTO.java
> +        @QueryProjection
QueryProjection으로 categories , tags를 제외한 생성자 커스텀을 위해서 사용하셨군요. Projections fields, constructor 같은 경우는 아무래도 정해진 형식대로 커스텀을 직접해내기가 까다롭긴 해보이긴 했는데, 잘 빼주신것 같습니다. 리플렉션을 통해서 사용되기떄문에 추후 유지보수 측면에서 관리면이나 불필요한 메모리를 잡아먹는 이슈도 있겠네요. Q파일이 생성되어놓고 사용을 하지 않게 되면 성능성 이슈도 있지 않나...라는 생각을 해봅니당

2021-05-21 16:49 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/domain/model/board/BoardRepository.java
> +    boolean existsByIdAndUserId(Long id, Long userId);
find시에 영속성 컨텍스트에 올라가고 JPA 1차 캐시에도 사용되니 비용적인 측면이 더 들 수도 있겠군요. 제가 생각하였던 부분은 Exists 같은경우도 결국 해당되는 모든 테이블을 셀렉해서 오고 exists도 영속성 컨텍스트에서 관리되고 해당 exists를 통해 셀렉된 값들이 결국엔 영속성 컨텍스트 자체에 존재하지 않을까 싶어서 이부분에 있어서 고민을 했던것 같네요. Optional에 대한 비용이 아무래도 boolean반환형 보다는 비용적인게 확실히 크긴 하겠군요 👍

2021-05-22 07:13 UTC, merged