feat: 카테고리 보드 동시 조회 API 및 테스트검증
DDD-5/null-moodof-backend pull request #50
Opened 2021-05-20 09:51 UTC by gwanhyeon

resolve #41 

카테고리 보드 동시조회시 QueryDSL 한꺼번에 서브쿼리로 fetch 해오려하였지만, 이슈발생하여 각각 조회후 리스트 넣는 과정까지 진행하였습니다. 
서브쿼리로 구현하고 싶었는데..한방쿼리로 연관관계가 없으니 가져오기가 힘드네요 🤦‍♂️ 이슈있으면 코멘트 부탁드리겠습니다 :)
- 카테고리 보드 동시 조회 API
- 통합테스트 TDD 검증

2021-05-21 07:29 UTC, kouz95 requested changes
한방 쿼리가 안되는건 저도 #44 작업하면서 겪은 부분입니다 🥲 (JPQL Projection 에서 Collection을 지원하지 않는다고 합니다.)
이후 개선을 하게 된다면 쌩 쿼리를 날릴 수 있는 수단을 만들어 QueryRepository에서 사용한다던지, 더 나아가면 쿼리 모델을 만들어낸다던지 할 수 있을 것 같습니다. (CQRS)

질문 주신 Category API 와 Category Board API의 경우엔,
저였다면 GET `/categories`에 Board까지 같이 넣어주는 API 하나만 만들것 같고, 이유는 필요하지 않은 API는 최대한 공개 하지 않는 것이 유지 보수에 용이하다고 생각하기 때문입니다.

고생하셨습니다! 리뷰 확인 부탁드립니다 🙇‍♂️

2021-05-21 07:29 UTC, kouz95 commented on src/main/java/com/ddd/moodof/application/CategoryService.java
> +        }
userId와 일치하는 카테고리가 없다면, 400 Bad Request를 응답하기보단 200 OK에 빈 body를 응답하는게 더 적절하다고 생각하는데 어떻게 생각하시나요?

2021-05-21 07:29 UTC, kouz95 commented on src/main/java/com/ddd/moodof/domain/model/category/CategoryRepository.java
> +    Optional<List<Category>> findCategoryByUserId(Long userId);
동작은 같지만, 저는 단건 조회일땐 findBy~, 리스트 조회일땐 findAllBy~로 명명하는 편입니다.
그리고 리스트 조회에서 조회 결과가 존재하지 않을땐 List가 비어 있음으로 확인 할 수 있다고 생각하기 때문에 Optional도 사용하지 않습니다.

2021-05-21 16:52 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/domain/model/category/CategoryRepository.java
> +    Optional<List<Category>> findCategoryByUserId(Long userId);
Optional을 걸어서 Exception을 처리할 생각으로 List에도 Optional을 걸어놓았는데 말씀들어보니 딱히 List건에 대해서굳이 Optional처리할 필요가 없겠군용!

2021-05-21 16:54 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/CategoryService.java
> +        }
400 Bad Request를 던져주면 클라이언트 입장에서도 Response에 대해서 헷갈릴 수 있는 부분이기도 해보이고 ok()를 떨궈주는 부분도 좋겠네요! 반영후에 리뷰 요청드리겠습니당

2021-05-22 07:32 UTC, kouz95 approved these changes

2021-05-22 07:32 UTC, merged