feat: 개수 및 길이 제한 구현
DDD-5/null-moodof-backend pull request #58
Opened 2021-05-26 13:40 UTC by kouz95

resolve #54 

- 사진 600장
- 카테고리 10개
- 카테고리 안 보드 최대 10개
- 보드 안에 이미지 50개
- 태그 최대 30개
- 휴지통 120개

---

- 카테고리 20자
- 보드 20자
- 태그 15자

2021-05-29 08:16 UTC, gwanhyeon requested changes
개수 및 길이 제한 구현 전체적으로 @Valid해놓으신부분 확인하였고, 개수 최소 @Min 정책에 있어서 고려도 필요해보입니다! 고생하셨습니다!

2021-05-29 08:16 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/adapter/presentation/BoardController.java
> +    public ResponseEntity<BoardDTO.BoardResponse> create(@LoginUserId Long userId, @Valid @RequestBody BoardDTO.CreateBoard request) {
@Valid부분을 전체적으로 처리해놓으셨는데, 앞으로 개발해놓는것들도 제약사항들 확인해서 @Valid를 적용시켜놓겠습니다.

2021-05-29 08:16 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/dto/BoardDTO.java
> +        @Max(value = 20, message = "보드의 최대 글자수는 20자 입니다.")
```suggestion
        @Max(value = 20, message = "보드의 최대 글자수는 20자 입니다.")
        @Min(value = 1, message="보드의 최소 글자수는 1자 입니다.")
```

최소글자에 대한 처리도 있어야하지 않을까요. 공백처리를 지금 프론트엔드딴에서 처리를 하고 있는건지 모르겠네용!

2021-05-29 08:16 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/dto/CategoryDTO.java
> +        @Max(value = 20, message = "카테고리의 최대 글자수는 20자 입니다.")
위와 @Min과 동일합니다.

2021-05-30 20:41 UTC, kouz95 commented on src/main/java/com/ddd/moodof/application/dto/BoardDTO.java
> +        @Max(value = 20, message = "보드의 최대 글자수는 20자 입니다.")
Max 밑에 `@NotBlank`가 있기 때문에 Min을 추가할 필요는 없다고 생각했습니다.

2021-05-30 20:42 UTC, kouz95 commented
실수로 Max를 사용하고 있었더라구요. Min Max는 숫자에 사용되는 validation인데 ㅜ..
테스트가 전부 실패하고 있어서 왜 그러지 한참 찾다가 발견하고 Length로 수정하였습니다.

2021-05-31 06:37 UTC, gwanhyeon commented on src/main/java/com/ddd/moodof/application/dto/BoardDTO.java
> +        @Max(value = 20, message = "보드의 최대 글자수는 20자 입니다.")
@NotBlank를 확인을 제대로 못했네요. @NotBlank가 있다면 굳이 추가할 필요는 없어보이네요.

2021-05-31 06:39 UTC, gwanhyeon approved these changes
@Max부분은 저도 순간적으로 실수할 수 있는 부분이였다고 생각이 듭니다. Length로 바꾸어서 바로 해결하셨다니 다행입니다 :) 특별한 사항없으면 머지 진행하셔도 좋을 것 같아요! 고생하셨습니다

2021-05-31 07:48 UTC, merged